//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baybak.TextReader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Baybak.TextReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;English&lt;/td&gt;
        ///    &lt;td&gt;
        ///      &lt;input id=&quot;eng&quot; type=&quot;text&quot; value=&quot;&quot;/&gt;
        ///    &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;Synonim&lt;/td&gt;
        ///    &lt;td&gt;
        ///      &lt;input id=&quot;syn&quot; type=&quot;text&quot; value=&quot;&quot;/&gt;
        ///    &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;Russian&lt;/td&gt;
        ///    &lt;td&gt;
        ///      &lt;textarea id=&quot;rus&quot; type=&quot;text&quot; rows=&quot;10&quot; cols=&quot;50&quot;&gt;&lt;/textarea&gt;
        ///    &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;Cancel&lt;/td&gt;
        ///    &lt;td onclick=&quot;window.external.Add2Dictionary()&quot;&gt;Add&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///&lt;/table&gt;
        ///.
        /// </summary>
        internal static string add2dic {
            get {
                return ResourceManager.GetString("add2dic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bfirst {
            get {
                object obj = ResourceManager.GetObject("bfirst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blast {
            get {
                object obj = ResourceManager.GetObject("blast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bnext {
            get {
                object obj = ResourceManager.GetObject("bnext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bprev {
            get {
                object obj = ResourceManager.GetObject("bprev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;English&lt;/td&gt;
        ///    &lt;td&gt;
        ///      &lt;input id=&quot;eng&quot; type=&quot;text&quot; value=&quot;&quot;/&gt;
        ///    &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;Synonim&lt;/td&gt;
        ///    &lt;td&gt;
        ///      &lt;input id=&quot;syn&quot; type=&quot;text&quot; value=&quot;&quot;/&gt;
        ///    &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;Russian&lt;/td&gt;
        ///    &lt;td&gt;
        ///      &lt;textarea id=&quot;rus&quot; type=&quot;text&quot; rows=&quot;10&quot; cols=&quot;50&quot;&gt;&lt;/textarea&gt;
        ///    &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;Cancel&lt;/td&gt;
        ///    &lt;td onclick=&quot;window.external.Add2Dictionary()&quot;&gt;Add&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///&lt;/table&gt;
        ///.
        /// </summary>
        internal static string canvas {
            get {
                return ResourceManager.GetString("canvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;style&gt;
        ///      input {
        ///      width:100%;
        ///      }
        ///      table {
        ///      width:100%;
        ///      }
        ///    &lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;script type=&quot;text/javascript&quot;&gt;
        ///    function saveBookInfo(){
        ///    var s = &quot;Author:&quot; + author.value
        ///    + &quot;;Title:&quot; + title.value
        ///    + &quot;;Comment:&quot; + comment.value;
        ///    window.external._saveBookInfo(file.innerText,s);
        ///    }
        ///  &lt;/script&gt;
        ///&lt;body&gt;
        ///  
        ///    &lt;table style=&quot;cursor:pointer;&quot;&gt;
        ///      &lt;tr&gt;
        ///        &lt;td&gt;Author&lt;/td&gt;
        ///        &lt;td&gt;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string editfileinfo {
            get {
                return ResourceManager.GetString("editfileinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fontminus {
            get {
                object obj = ResourceManager.GetObject("fontminus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fontplus {
            get {
                object obj = ResourceManager.GetObject("fontplus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap google {
            get {
                object obj = ResourceManager.GetObject("google", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;&lt;/head&gt;
        ///&lt;body&gt;
        ///  
        ///    &lt;table style=&quot;width:100%;cursor:pointer;&quot;&gt;
        ///      &lt;tr&gt;
        ///        &lt;th&gt;Author&lt;/th&gt;
        ///        &lt;th&gt;Title&lt;/th&gt;
        ///        &lt;th&gt;Comment&lt;/th&gt;
        ///        &lt;th&gt;File&lt;/th&gt;
        ///      &lt;/tr&gt;
        ///      $
        ///      &lt;tr&gt;
        ///        &lt;td&gt;@Author&lt;/td&gt;
        ///        &lt;td&gt;@Title&lt;/td&gt;
        ///        &lt;td&gt;@Comment&lt;/td&gt;
        ///        &lt;td onclick=&quot;window.external._openFile(this.innerText)&quot;&gt;@File&lt;/td&gt;
        ///        &lt;td onclick=&quot;window.external._editFileInfo(&apos;@File&apos;)&quot;&gt;Edit&lt;/td&gt;
        ///      &lt;/tr&gt;
        ///      $
        ///    &lt;/table&gt;
        ///&lt;/bod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///function saveBookInfo2(){
        ///    var s = &quot;Author:&quot; + author.value 
        ///        + &quot;;Title:&quot; + title.value 
        ///        + &quot;;Comment:&quot; + comment.value;
        ///        alert(s);
        ///    }
        ///.
        /// </summary>
        internal static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;script type=&quot;text/javascript&quot;&gt;
        ///  &lt;/script&gt;
        ///&lt;body&gt;
        ///  &lt;input id=&quot;txt&quot; type=&quot;text&quot; value=&quot;{{TEXT}}&quot;/&gt;
        ///  &lt;button  onclick=&quot;window.external.Translate(txt.value)&quot;&gt;translate&lt;/button&gt;
        ///  &lt;div id=&quot;result&quot; style=&quot;width:100%;&quot;&gt;1234&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string tr {
            get {
                return ResourceManager.GetString("tr", resourceCulture);
            }
        }
    }
}
